name: Create APK Release
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - release
      - feature/github-actions-release
jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        WITH_V: true
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Execute Flutter Build
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Execute Flutter Build
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows
    
