name: CI/CD Release
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - release
      - feature/github-actions-release
jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.checkTag.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      id: checkTag
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        WITH_V: true
    - name: Print created tag
      run: "echo ${{ steps.checkTag.outputs.new_tag }}"
        
  build-apk:
    runs-on: ubuntu-latest
    needs:
    - check-tag
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Execute Flutter Build
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: flutter pub get
    - run: flutter build apk
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-android.apk
        path:  build/app/outputs/flutter-apk/app-release.apk
    
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
    - check-tag
    - build-apk
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    - name: Output downloaded files
      run: ls -la
      working-directory: ./artifacts
    - name: Create Release
      id: createRelease
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*.apk"
        tag: ${{ needs.check-tag.outputs.tag }}
        name: CI/CD Automatic Release ${{ needs.check-tag.outputs.tag }}
        generateReleaseNotes: true
    - name: Output Created Release ID
      run: "echo Created release with id ${{ steps.createRelease.outputs.id }}"
      
